# Generated by Django 5.2.6 on 2025-10-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_contato', models.EmailField(default='contato@radarbr.com.br', help_text='E-mail principal para contato', max_length=255)),
                ('email_redacao', models.EmailField(default='redacao@radarbr.com.br', help_text='E-mail da redação', max_length=255)),
                ('telefone', models.CharField(blank=True, help_text='Telefone de contato (opcional)', max_length=20)),
                ('endereco', models.TextField(blank=True, help_text='Endereço físico (opcional)')),
                ('facebook_url', models.URLField(blank=True, help_text='URL do Facebook', max_length=500)),
                ('twitter_url', models.URLField(blank=True, help_text='URL do Twitter/X', max_length=500)),
                ('instagram_url', models.URLField(blank=True, help_text='URL do Instagram', max_length=500)),
                ('youtube_url', models.URLField(blank=True, help_text='URL do YouTube', max_length=500)),
                ('linkedin_url', models.URLField(blank=True, help_text='URL do LinkedIn', max_length=500)),
                ('telegram_url', models.URLField(blank=True, help_text='URL do Telegram', max_length=500)),
                ('nome_site', models.CharField(default='RadarBR', help_text='Nome do site', max_length=100)),
                ('slogan', models.CharField(default='Suas notícias em tempo real', help_text='Slogan do site', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
