# Generated by Django 5.2.6 on 2025-09-20 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('conteudo', models.TextField()),
                ('fonte_nome', models.CharField(max_length=120)),
                ('fonte_url', models.URLField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('imagem_alt', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], default='published', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('publicado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='rb_noticias.categoria')),
            ],
            options={
                'ordering': ['-publicado_em'],
            },
        ),
    ]
