# Generated by Django 5.2.6 on 2025-09-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagem_credito',
            field=models.CharField(blank=True, max_length=255, verbose_name='Crédito da imagem'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagem_fonte_url',
            field=models.URLField(blank=True, verbose_name='URL da imagem (fonte)'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagem_licenca',
            field=models.CharField(blank=True, max_length=80, verbose_name='Licença da imagem'),
        ),
    ]
