# Generated by Django 5.2.6 on 2025-09-29 03:57

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('rb_noticias', '0002_noticia_imagem_credito_noticia_imagem_fonte_url_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # não mexe no banco (a coluna já existe)
            state_operations=[
                migrations.AddField(
                    model_name='noticia',
                    name='status',
                    field=models.IntegerField(
                        default=1,
                        choices=[(0, 'rascunho'), (1, 'publicado')],
                        db_column='status',
                    ),
                ),
            ],
        ),
    ]
