# Generated by Django 5.2.6 on 2025-09-29 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_noticias', '0003_attach_status_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-publicado_em'], 'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rb_noticias.categoria'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fonte_nome',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fonte_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem_alt',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem_credito',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem_fonte_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem_licenca',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='publicado_em',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='status',
            field=models.IntegerField(choices=[(0, 'Rascunho'), (1, 'Publicado')], default=1),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
