# Generated by Django 5.2.6 on 2025-09-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_noticias', '0004_alter_categoria_options_alter_noticia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fonte_url',
            field=models.CharField(blank=True, default='', max_length=300, unique=True),
        ),
    ]
