# Generated by Django 5.2.6 on 2025-10-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_noticias', '0005_alter_noticia_fonte_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fonte_url',
            field=models.URLField(blank=True, default='', max_length=1000, unique=True),
        ),
    ]
