# Generated by Django 5.0.1 on 2025-01-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_noticias', '0007_alter_noticia_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem da notícia', null=True, upload_to='noticias/'),
        ),
    ]
