# Generated by Django 5.0.1 on 2025-01-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_noticias', '0009_alter_noticia_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.URLField(blank=True, help_text='URL da imagem da notícia (Wikimedia, Openverse, etc.)', max_length=1000, null=True),
        ),
    ]
