# Generated by Django 5.2.6 on 2025-10-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rb_noticias', '0002_fix_status_field_type'),
        ('rb_noticias', '0010_alter_noticia_imagem'),
    ]

    operations = [
    ]
