# Generated by Django 5.2.6 on 2025-10-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_noticias', '0011_merge_20251012_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='destaque',
            field=models.BooleanField(default=False, help_text='Se marcado, esta notícia será exibida como destaque no topo da home'),
        ),
    ]
