# Generated by Django 5.2.6 on 2025-10-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_noticias', '0012_noticia_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='clicks',
            field=models.PositiveIntegerField(default=0, help_text='Número de cliques na notícia'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='shares',
            field=models.PositiveIntegerField(default=0, help_text='Número de compartilhamentos'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='trending_score',
            field=models.FloatField(default=0.0, help_text='Score calculado para trending (atualizado automaticamente)'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Número de visualizações da notícia'),
        ),
    ]
