# Generated by Django 5.2.6 on 2025-10-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_noticias', '0013_noticia_clicks_noticia_shares_noticia_trending_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='show_youtube',
            field=models.BooleanField(default=False, help_text='Se marcado, exibe os vídeos do YouTube neste artigo'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='youtube_urls',
            field=models.TextField(blank=True, default='', help_text='Cole uma ou mais URLs do YouTube, uma por linha'),
        ),
    ]
