# Generated by Django 5.2.6 on 2025-09-16 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.CharField(blank=True, max_length=240)),
                ('content', models.TextField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('cover_alt', models.CharField(blank=True, max_length=180)),
                ('source_name', models.CharField(blank=True, max_length=120, verbose_name='Fonte (nome)')),
                ('source_url', models.URLField(blank=True, verbose_name='Fonte (URL)')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='siteapp.category')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['slug'], name='siteapp_pos_slug_74ff7d_idx'), models.Index(fields=['is_published', 'published_at'], name='siteapp_pos_is_publ_c9eb39_idx')],
            },
        ),
    ]
